dw donkey_rope_double_hitbox		;4270
dw donkey_rope_double_hitbox		;4274
dw donkey_rope_double_hitbox		;4278
dw donkey_rope_double_hitbox		;427C
dw donkey_rope_double_hitbox		;4280
dw donkey_rope_double_hitbox		;4284
dw donkey_rope_double_hitbox		;4288
dw donkey_rope_double_hitbox		;428C

dw donkey_rope_double_hitbox		;4290
dw donkey_rope_double_hitbox		;4294
dw donkey_rope_double_hitbox		;4298
dw donkey_rope_double_hitbox		;429C
dw donkey_rope_double_hitbox		;42A0
dw donkey_rope_double_hitbox		;42A4
dw donkey_rope_double_hitbox		;42A8
dw donkey_rope_double_hitbox		;42AC

dw donkey_rope_single_to_double_hitbox	;42B0
dw donkey_rope_single_to_double_hitbox	;42B4
dw donkey_rope_single_to_double_hitbox	;42B8
dw donkey_rope_single_to_double_hitbox	;42BC
dw donkey_rope_single_to_double_hitbox	;42C0
dw donkey_rope_single_to_double_hitbox	;42C4
dw donkey_rope_single_to_double_hitbox	;42C8
dw donkey_rope_double_hitbox		;42CC
dw donkey_rope_double_hitbox		;42D0
dw donkey_rope_double_hitbox		;42D4
dw donkey_rope_double_hitbox		;42D8

dw donkey_wind_float_hitbox		;42DC
dw donkey_wind_float_hitbox		;42E0
dw donkey_wind_float_hitbox		;42E4
dw donkey_wind_float_hitbox		;42E8
dw donkey_wind_float_hitbox		;42EC
dw donkey_wind_float_hitbox		;42F0
dw donkey_wind_float_hitbox		;42F4
dw donkey_wind_float_hitbox		;42F8
dw donkey_wind_float_hitbox		;42FC
dw donkey_wind_float_hitbox		;4300
dw donkey_wind_float_hitbox		;4304
dw donkey_wind_float_hitbox		;4308

dw donkey_honey_wall_hitbox		;430C
dw donkey_honey_wall_hitbox		;4310
dw donkey_honey_wall_hitbox		;4314
dw donkey_honey_wall_hitbox		;4318

dw donkey_hook_hitbox			;431C
dw donkey_hook_hitbox			;4320
dw donkey_hook_hitbox			;4324
dw donkey_hook_hitbox			;4328
dw donkey_hook_hitbox			;432C
dw donkey_hook_hitbox			;4330
dw donkey_hook_hitbox			;4334
dw donkey_hook_hitbox			;4338
dw donkey_hook_hitbox			;433C
dw donkey_hook_hitbox			;4340
dw donkey_hook_hitbox			;4344
dw donkey_hook_hitbox			;4348
dw donkey_hook_hitbox			;434C

dw donkey_h_rope_idle_hitbox		;4350
dw donkey_h_rope_idle_hitbox		;4354
dw donkey_h_rope_idle_hitbox		;4358
dw donkey_h_rope_idle_hitbox		;435C
dw donkey_h_rope_idle_hitbox		;4360
dw donkey_h_rope_idle_hitbox		;4364
dw donkey_h_rope_idle_hitbox		;4368
dw donkey_h_rope_idle_hitbox		;436C

dw donkey_h_rope_move_hitbox		;4370
dw donkey_h_rope_move_hitbox		;4374
dw donkey_h_rope_move_hitbox		;4378
dw donkey_h_rope_move_hitbox		;437C
dw donkey_h_rope_move_hitbox		;4380
dw donkey_h_rope_move_hitbox		;4384
dw donkey_h_rope_move_hitbox		;4388
dw donkey_h_rope_move_hitbox		;438C
dw donkey_h_rope_move_hitbox		;4390
dw donkey_h_rope_move_hitbox		;4394
dw donkey_h_rope_move_hitbox		;4398
dw donkey_h_rope_move_hitbox		;439C
dw donkey_h_rope_move_hitbox		;43A0
dw donkey_h_rope_move_hitbox		;43A4
dw donkey_h_rope_move_hitbox		;43A8

dw donkey_team_bottom_hitbox		;43AC
dw donkey_team_bottom_hitbox		;43B0
dw donkey_team_bottom_hitbox		;43B4
dw donkey_team_bottom_hitbox		;43B8
dw donkey_team_bottom_hitbox		;43BC
dw donkey_team_bottom_hitbox		;43C0
dw donkey_team_bottom_hitbox		;43C4
dw donkey_team_bottom_hitbox		;43C8
dw donkey_team_bottom_hitbox		;43CC
dw donkey_team_bottom_hitbox		;43D0
dw donkey_team_bottom_hitbox		;43D4
dw donkey_team_bottom_hitbox		;43D8
dw donkey_team_bottom_hitbox		;43DC
dw donkey_team_bottom_hitbox		;43E0
dw donkey_team_bottom_hitbox		;43E4
dw donkey_team_bottom_hitbox		;43E8
dw donkey_team_bottom_hitbox		;43EC
dw donkey_team_bottom_hitbox		;43F0
dw donkey_team_bottom_hitbox		;43F4

dw donkey_squawks_idle_hitbox		;43F8
dw donkey_squawks_idle_hitbox		;43FC
dw donkey_squawks_idle_hitbox		;4400
dw donkey_squawks_idle_hitbox		;4404
dw donkey_squawks_idle_hitbox		;4408
dw donkey_squawks_idle_hitbox		;440C