!bgm_loc 		= $1300			;Starting ARAM location of music block (default: $1300)
!bgm_ptr_loc		= !bgm_loc+$12		;Starting ARAM location of music pointers (default: $1312)

!snd_loc 		= $2410			;Starting ARAM location of global sound effect block (default: $2410)
!snd_ptr_loc		= !snd_loc+$2		;Starting ARAM location of global sound effect pointers (default: $2412)

!dyn_snd_loc 		= $2E10			;Starting ARAM location of track-specific sound effect block (default: $2E94)
!dyn_snd_ptr_loc	= !dyn_snd_loc+$2	;Starting ARAM location of track-specific sound effect pointers (default: $2E96)
!dyn_snd_base_id	= $60			;Base ID of track-specific sound effects (default: $60)

!src_dir_loc		= $3100			;Starting ARAM destination of BRR sample source directory (default: $3100)
!brr_data_loc		= $3400			;Starting ARAM destination of BRR sample uploads (default: $3400)

!end_sequence 			= $00	;00				End of sequence
!set_instrument 		= $01	;01 ??				Set instrument
!set_volume_l_and_r 		= $02	;02 LL RR			Set volume levels (separate values for left and right speakers)
!jump_to_sequence 		= $03	;03 yy XX			Jump to sequence data at SPC RAM address XXyy
!loop_subsequence 		= $04	;04 NN yy XX			Play subsequence at SPC RAM address XXyy NN times
!return_from_sub 		= $05	;05				End of subsequence (return to main)
!set_default_duration		= $06	;06 ??				Set and enable default note duration (if not set, must specify a note length after each note value)
!default_duration_off 		= $07	;07				Disable default note duration
!pitch_slide_up 		= $08	;08 ?? ?? ?? ?? ??   		Pitch slide up
!pitch_slide_down 		= $09	;09 ?? ?? ?? ?? ??		Pitch slide down
!pitch_slide_off 		= $0A	;0A				Pitch slide off
!change_tempo 			= $0B	;0B ??				Change tempo
!change_tempo_rel 		= $0C	;0C ??				Increase/decrease tempo relative to current tempo
!vibrato 			= $0D	;0D XX YY ZZ			Vibrato (XX = Range, YY = Rate, ZZ = depth)
!vibrato_off 			= $0E	;0E
!vibrato_with_delay 		= $0F	;0F XX YY ZZ TT			Vibrato (same as 0D, but with TT = delay)
!set_adsr 			= $10	;10 ?? ??			Attack/decay/sustain/release (ADSR) of current instrument
!set_master_volume 		= $11	;11 LL RR			Master level (LL = left, RR = right; valid range: #$00-#$7F) 
!fine_tune 			= $12	;12 ??				Fine tune (signed)
!change_instr_pitch		= $13	;13 ??				Set instrument pitch (signed)
!change_instr_pitch_rel		= $14	;14 ??				Increase/decrease instrument pitch relative to current pitch (signed)
!set_echo 			= $15	;15 KK LL RR			Echo of entire song (KK = feedback, LL = left echo level, RR = right echo level)
!echo_on 			= $16	;16				Echo on
!echo_off 			= $17	;17				Echo off
!set_fir 			= $18	;18 ?? ?? ?? ?? ?? ?? ?? ??	Finite impulse response (FIR) filter for whole song
!dsp_flag 			= $19	;19 ??
!noise_on 			= $1A	;1A
!noise_off 			= $1B	;1B
!set_variable_note_1 		= $1C	;1C ??				?? is the note value that note $E0 will play
!set_variable_note_2 		= $1D	;1D ??				?? is the note value that note $E1 will play
!set_volume_presets		= $1E	;1E LL RR ll rr			LL and RR = left and right levels of volume preset 1; ll and rr = left and right levels of volume preset 2
!echo_delay			= $1F	;1F ??
!load_volume_preset_1 		= $20	;20				Set volume to first and second bytes of command 1E?
!play_subsequence 		= $21	;21 yy XX			Play subsequence at SPC RAM address XXyy once
!set_voice_parameters 		= $22	;22 ?? ?? ?? ?? ?? ?? ??
!set_vol_single_val		= $23	;23 ??				Set volume Levels (same value for both speakers, DKC2 & 3 only)
!set_master_volume_indirect	= $24	;24 ??
!audio_command_25 		= $25	;unimplemented command
!simple_pitch_slide_down 	= $26	;26 ?? ?? ?? ?? ??
!simple_pitch_slide_up 		= $27	;27 ?? ?? ?? ?? ??
!audio_command_28 		= $28	;unimplemented command
!audio_command_29 		= $29	;unimplemented command
!audio_command_2A 		= $2A	;unimplemented command
!long_duration_on 		= $2B	;2B
!long_duration_off 		= $2C	;2C
!audio_command_2D 		= $2D	;unimplemented command
!audio_command_2E 		= $2E	;unimplemented command
!audio_command_2F 		= $2F	;unimplemented command
!echo_off_copy_1 		= $30	;30				Duplicate of 17, 32
!load_volume_preset_2 		= $31	;31				Set volume to third and fourth bytes of command 1E?
!echo_off_copy_2		= $32	;32				Duplicate of 17, 30

!rest = $80				;frequency: $0000
!note_81 = $81
!note_82 = $82
!note_83 = $83
!note_84 = $84
!note_85 = $85
!note_86 = $86
!note_87 = $87
!note_88 = $88
!note_89 = $89
!note_8A = $8A
!note_8B = $8B
!note_8C = $8C
!note_8D = $8D
!note_8E = $8E
!note_8F = $8F
!note_90 = $90
!note_91 = $91
!note_92 = $92
!note_93 = $93
!note_94 = $94
!note_95 = $95
!note_96 = $96
!note_97 = $97
!note_98 = $98
!note_99 = $99
!note_9A = $9A
!note_9B = $9B
!note_9C = $9C
!note_9D = $9D
!note_9E = $9E
!note_9F = $9F
!note_A0 = $A0
!note_A1 = $A1
!note_A2 = $A2
!note_A3 = $A3
!note_A4 = $A4
!note_A5 = $A5
!note_A6 = $A6
!note_A7 = $A7
!note_A8 = $A8
!note_A9 = $A9
!note_AA = $AA
!note_AB = $AB
!note_AC = $AC
!note_AD = $AD
!note_AE = $AE
!note_AF = $AF
!note_B0 = $B0
!note_B1 = $B1
!note_B2 = $B2
!note_B3 = $B3
!note_B4 = $B4
!note_B5 = $B5
!note_B6 = $B6
!note_B7 = $B7
!note_B8 = $B8
!note_B9 = $B9
!note_BA = $BA
!note_BB = $BB
!note_BC = $BC
!note_BD = $BD
!note_BE = $BE
!note_BF = $BF
!note_C0 = $C0
!note_C1 = $C1
!note_C2 = $C2
!note_C3 = $C3
!note_C4 = $C4
!note_C5 = $C5
!note_C6 = $C6
!note_C7 = $C7
!note_C8 = $C8
!note_C9 = $C9
!note_CA = $CA
!note_CB = $CB
!note_CC = $CC
!note_CD = $CD
!note_CE = $CE
!note_CF = $CF
!note_D0 = $D0
!note_D1 = $D1
!note_D2 = $D2
!note_D3 = $D3
!note_D4 = $D4
!note_D5 = $D5
!note_D6 = $D6
!note_D7 = $D7
!note_D8 = $D8
!note_D9 = $D9
!note_DA = $DA
!note_DB = $DB
!note_DC = $DC
!note_DD = $DD
!note_DE = $DE
!note_DF = $DF
!note_E0 = $E0		;Note: E0 is special; it maps to whatever note value is specified by command $1C
!note_E1 = $E1		;Note: E1 is special; it maps to whatever note value is specified by command $1D